### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by bishtawi** [bjyoungblood/rnr-constrained-route#5]
Im using the latest version of react and react router, and rnr-constrained-route does not seem to work at all.

**Comment by bjyoungblood** [comment]
I personally haven't used this project since react-router v0.4 or so. I'll try to take a look at what the issue is soon, but I'd also accept a pull request.

It would also be helpful if you could provide some details such as a stack trace or an example.

**Comment by bishtawi** [comment]
I have since moved away from this plugin and just implemented something myself. But when I was looking into it, there wasnt any errors to go off of and I didnt feel like doing any debugging. Sorry.
